# An extremely minimal configuration which only enables you to set the boiler's
# water temperature setpoint as a number.

esphome:
  name: thermostat-number-minimal

external_components:
  # Replace with a direct reference to GitHub in your own configuration
  #source: github://arthurrump/esphome-opentherm@main
  source: 
    type: local
    path: ../components

esp8266:
  board: d1_mini

logger:

api:
ota:
wifi:
  ap:
    ssid: "Thermostat"
    password: "MySecretThemostat"
captive_portal:

opentherm:

number:
  - platform: opentherm
    t_set:
      name: "Boiler Control setpoint"
