name: build

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: esphome/esphome:latest
    steps:
      - uses: actions/checkout@v3
      - run: pip3 install mypy
      - run: mypy
      - run: python3 compile_all.py
