name: build

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: esphome/esphome:latest
    steps:
      - uses: actions/checkout@v3
      - run: compile_all.py
        shell: python
